name: OpenWrt Build

on:
  push:

env:
  PACKAGE_NAME: luci-app-v2ray

jobs:
  build:
    name: luci-app-v2ray all build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - openwrt-21.02
          # - openwrt-22.03
        arch:
          - arm_cortex-a7
          # - arm_cortex-a9

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 2
          path: luci-app-v2ray

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEED_DIR: ${{ github.workspace }}
          PACKAGES: ${{ env.PACKAGE_NAME }}

      - name: Store packages
        uses: actions/upload-artifact@v3
        with:
          name: luci-app-v2ray-all-packages
          path: bin/packages/${{ matrix.arch }}/action/*.ipk
